# Workflow for cleaning up deployed Shiny apps after PR closure
name: Cleanup PR deployment

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Delete app
        env:
          SHINY_APP_NAME: ${{ vars.SHINY_APP_NAME }}_PR_${{ github.event.pull_request.number }}
        run: |
          install.packages("rsconnect")
          rsconnect::setAccountInfo("${{ vars.SHINY_ACCOUNT }}", "${{ secrets.SHINY_TOKEN }}", "${{ secrets.SHINY_SECRET }}")
          rsconnect::terminateApp(appName = "${{ env.SHINY_APP_NAME }}", account = "${{ vars.SHINY_ACCOUNT }}")
          rsconnect::purgeApp(appName = "${{ env.SHINY_APP_NAME }}", account = "${{ vars.SHINY_ACCOUNT }}")
        shell: Rscript {0}
