# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# see https://www.tidyverse.org/blog/2022/06/actions-2-0-0/ for info on setup-r-dependencies@v2
on:
  push:
    branches: [main, master]
  workflow_dispatch:

name: Deployment Production

jobs:
  deployment-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://stanpumpr.io
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::remotes
            any::rsconnect

      - name: Install stanpumpR from GitHub
        run: |
          pkg_ref <- "${{ github.repository }}"
          remotes::install_github(pkg_ref, upgrade = "never", force = TRUE)
        shell: Rscript {0}

      - name: Authorize and deploy app
        run: |
          shinyConfig <- list(
            default = list(
              email_username = "${{ secrets.SHINY_CONFIG_EMAIL_USERNAME }}",
              email_password = "${{ secrets.SHINY_CONFIG_EMAIL_PASSWORD }}",
              debug = 0
            )
          )
          yaml::write_yaml(shinyConfig, "config.yml", fileEncoding = "UTF-8")
          rsconnect::setAccountInfo("${{ vars.SHINY_ACCOUNT }}", "${{ secrets.SHINY_TOKEN }}", "${{ secrets.SHINY_SECRET }}")
          rsconnect::deployApp(
            appName = "${{ vars.SHINY_APP_NAME }}", account = "${{ vars.SHINY_ACCOUNT }}",
            appDir = ".", appFiles = c("app.R", "config.yml"), forceUpdate = TRUE
          )
        shell: Rscript {0}
