# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# see https://www.tidyverse.org/blog/2022/06/actions-2-0-0/ for info on setup-r-dependencies@v2
on:
  pull_request_target:
    branches: [main, master]
  workflow_dispatch:

name: Deployment PR

jobs:
  deployment-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        env:
          PKG_INCLUDE_LINKINGTO: "true"
        with:
          cache-version: 2
          extra-packages: |
            any::rsconnect

      - name: Authorize and deploy app
        env:
          SHINY_APP_NAME: ${{ secrets.SHINY_APP_NAME }}_PR_${{ github.event.pull_request.number }}
        run: |
          shinyConfig <- list(
            default = list(
              title = 'stanpumpR',
              email_username = "${{ secrets.SHINY_CONFIG_EMAIL_USERNAME }}",
              email_password = "${{ secrets.SHINY_CONFIG_EMAIL_PASSWORD }}"
            )
          )
          yaml::write_yaml(shinyConfig, "config.yml", fileEncoding = "UTF-8")
          rsconnect::setAccountInfo("${{ secrets.SHINY_ACCOUNT }}", "${{ secrets.SHINY_TOKEN }}", "${{ secrets.SHINY_SECRET }}")
          rsconnect::deployApp(appName = "${{ env.SHINY_APP_NAME }}", account = "${{ secrets.SHINY_ACCOUNT }}", forceUpdate = TRUE)
        shell: Rscript {0}
