# Workflow for cleaning up deployed Shiny apps after PR closure
name: Cleanup PR deployment

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: r-lib/actions/setup-r@v2

      - name: Install rsconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}

      - name: Delete app
        env:
          SHINY_APP_NAME: ${{ secrets.SHINY_APP_NAME }}_PR_${{ github.event.pull_request.number }}
        run: |
          rsconnect::setAccountInfo("${{ secrets.SHINY_ACCOUNT }}", "${{ secrets.SHINY_TOKEN }}", "${{ secrets.SHINY_SECRET }}")
          rsconnect::terminateApp(appName = "${{ env.SHINY_APP_NAME }}", account = "${{ secrets.SHINY_ACCOUNT }}")
        shell: Rscript {0}
